config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'


  get '/today' => 'pages#show'
  get '/today/update' => 'pages#update'
  post '/today' => 'pages#create'

  resources :entries
  resources :items 
  resources :users, only: [:new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user, optional: true

  has_many :items
  accepts_nested_attributes_for :items, allow_destroy: true

  scope :todays_entries, -> { where(date: Date.today)
                              .map { |entry| entry.items }
                              .flatten }
          
  scope :specific_entries, -> (date) { where("(date) = ?", date)
                              .map { |entry| entry.items }
                              .flatten }
          
  
end
# 

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :entry, optional: true
  before_save :update_energy
  
  def update_energy
    self.energy ||= (self.protein * 4) + (self.carb * 4) + (self.fat * 9)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  has_many :entries
  has_many :items, through: :entries
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  private
    def fetch_user
      @current_user = User.find_by id: session[:user_id] if session[:user_id].present?
      session[:user_id] = nil unless @current_user.present?
    end

    def check_for_login
      redirect_to  login_path unless @current_user.present?
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :check_for_login
  
  def new
    @item = Item.new
    @entry = Entry.new
  end

  def create
    @entry = Entry.create entry_params
    @item = @entry.items.create item_params
    if @entry.save
      redirect_to today_path
    end
  end

  def update
  end
  
  def edit
  end

  private
    def entry_params
      params.require(:entry).permit(:user_id, :date, :items => [])
    end

    def item_params
      params.require(:items).permit(:protein, :fat, :carb, :name)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :check_for_login
  
  def new
    @item = Item.new
    @entry = Entry.new
  end

  def create
    @entry = Entry.create entry_params
    @item = @entry.items.create item_params

  end

  def update
    @item = Item.find params[:id]
    @item.update item_params
    redirect_to today_path
  end

  def edit
    @item = Item.find params[:id]
  end

  def destroy
    item = Item.find params[:id]
    item.destroy
  end

  private
  def item_params
    params.require(:item).permit(:id, :name, :protein, :carb, :fat, :entry_id, :energy)
  end
  def entry_params
    params.require(:entry).permit(:user_id, :date, :items => [])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :check_for_login, :only => [:show, :update]
  
  def home
  end

  def show
    @user = User.find_by email: @current_user.email
  end
  
  def update
    @date = Date.parse( params[:date] )
    @user = User.find_by email: @current_user.email
    
    render :update, :layout => false
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by email: params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to today_path
    else
      flash[:error] = "Invalid Username or Password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_login, :only => [:update, :edit]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to today_path
    else
      render :new
    end
  end

  def update
    user = User.find @current_user.id
    user.update user_params
    if user.save
      flash[:message] = "Details updated"
    end
    redirect_to edit_user_path
  end

  def edit
    @user = User.find @current_user.id
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :gender, :height, :weight, :activity_level, :goal, :target_intake)
  end
end

app/views/entries/_form.html.erb
<%= form_for @entry, id: "new-entry" do |f| %>
  <%= f.hidden_field :user_id, value: @current_user.id %>
  <%= f.hidden_field :date, value: Date.today.strftime( "%Y-%m-%d" ) %>

  <%= fields_for :items, @entry.items do |i| %>
  <fieldset>
    <%= i.label :protein, class: "label" %>
    <%= i.range_field :protein,
                      value: 1,
                      min: 0,
                      max: 200,
                      id: "protein-slider",
                      class: "slider is-fullwidth is-info is-large has-output"%>
    <output for="protein-slider" id="protein-output">1</output>  
                 
    <%= i.label :carb, class: "label" %>
    <%= i.range_field :carb,
                      value: 1,
                      min: 0,
                      max: 200,
                      id: "carb-slider",
                      class: "slider is-fullwidth is-success is-large has-output"%>
    <output for="carb-slider" id="carb-output">1</output>   

    <%= i.label :fat, class: "label" %>
    <%= i.range_field :fat,
                      value: 1,
                      min: 0,
                      max: 200,
                      id: "fat-slider",
                      class: "slider is-fullwidth is-warning is-large has-output"%>
    <output for="fat-slider" id="fat-output">1</output>               

    <div class="field has-addons">

      <div class="control is-expanded">
        <%= i.text_field :name, class: "input is-info is-large is-rounded", placeholder: "name" %>
      </div>


  <% end %>
      <div class="control">
        <%= f.submit "add", id: "new-item-submit", class: "button is-large is-info is-rounded" %>
      </div>

    </div>
  </fieldset>
  <br>

<% end %>

app/views/entries/new.html.erb
<h1 class="title is-1">New Entry</h1>

<%= render partial: 'form' %>
<script>

$( document ).ready( function() {
  $( "#fat-slider" ).mousemove( function() {
    $( "#fat-output" ).text($( '#fat-slider' ).val() )
  })

  $( "#protein-slider" ).mousemove( function() {
    $( "#protein-output" ).text( $( '#protein-slider' ).val() )
  })

  $( "#carb-slider" ).mousemove( function() {
    $( "#carb-output" ).text( $('#carb-slider').val() )
  })

})
</script>

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <div class="field">
    <%= f.label :name, class: "label"%>
    <div class="control">
      <%= f.text_field :name, required: true, autofocus: true, class: "input is-rounded" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :protein, class: "label" %>
    <div class="control">
      <%= f.number_field :protein, required: true, class: "input is-rounded" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :carb, "Carbohydrate", class: "label" %>
    <div class="control">
      <%= f.text_field :carb, required: true, class: "input is-rounded" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :fat, class: "label" %>
    <div class="control">
      <%= f.number_field :fat, required: true, class: "input is-rounded" %>
    </div>
  </div>
  
  <div class="field">
    <%= f.label :energy, class: "label" %>
    <div class="control">
      <%= f.number_field :energy, required: true, class: "input is-rounded" %>
    </div>
  </div>
  
  <div class="field">
    <div class="control">
      <%= f.submit class: "button is-link is-rounded" %>
    </div>
  </div>
  
<% end %>

app/views/items/edit.html.erb
<h1 class="title is-1">Edit your item</h1>
<%= render partial: "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>UNA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <% if @current_user.present? %> 
              <%= link_to 'Home', today_path, class: "button is-warning" %> 
              <%= link_to 'Add', new_entry_path, class: "button is-link" %>

              <%= link_to 'Settings', edit_user_path(@current_user), class: "button is-light" %> 
              <%= link_to "Log Out", login_path, method: 'delete', class: "button is-light" %>
            <% end %>
          </div>
      </div>
    </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_calendar.html.erb
<div class="field has-addons">

  <div class="control">
    <%= hidden_field_tag :date_value %>
    <input id="datepicker" class="input" type="date" placeholder="Search another day?">
  </div>

  <div class="control">
    <%= link_to today_path, remote: true, id: "calendar-button", class: "button is-link" do %>
      <p>GO</p>
    <% end %>
  </div>

</div>

app/views/pages/_data.html.erb
  <%= pie_chart ({ Intake: @user.entries.todays_entries.map(&:energy).sum,
                   Remaining: @user.target_intake - @user.entries.todays_entries.map(&:energy).sum }),
                   colors: ["#48C774","#DDF5E5"],
                   height: "500px",
                   library: {fontSize: "30px"}
                  %>
  <%= pie_chart ({ Protein: @user.entries.todays_entries.map(&:protein).sum,
                   Carbohydrate: @user.entries.todays_entries.map(&:carb).sum, 
                   Fat: @user.entries.todays_entries.map(&:fat).sum }),
                   colors: ["#34B5E1", "#FFDD57", "#FD5F7E"],
                   donut: true %>

<br>
<br>

<div class="tile is-ancestor">
  <div class="tile is-vertical is-parent is-vertical">
    <% @user.entries.todays_entries.each do |entry| %>

      <div class="tile is-child notification is-light">

        <p class="title"><%= entry.name %></p>
        <p class="subtitle"><%= entry.energy %> Kcal</p>

        <div class="subtitle is-6">
          <%= entry.protein %> P | <%= entry.carb %> C | <%= entry.fat %> F
        </div>

        <nav class="level is-mobile">
          <div class="level-left">
            <%= link_to edit_item_path(entry.id),
                        class: "level-item",
                        "aria-label": "edit" do %>

              <span class="icon is-small">
                <%= fa_icon "edit" %>
              </span>

            <% end %>

            <%= link_to item_path(entry.id), 
                        method: "delete",
                        class: "level-item",
                        "aria-label": "delete" do %>

              <span class="icon is-small">
                <%= fa_icon "trash" %>
              </span>
              
            <% end %>
          </div>
        </nav>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/_entries.html.erb
<h1 class="title is-1">
  
  <% if @current_user.name.present? %>
    Hi <%= @current_user.name.split.first %>!
  <% else %>
    Hi!
  <% end %>
  
</h1>

<h2 class="subtitle is-3">
  You're viewing <%= Date.today.strftime("%A, %e %b") %>
</h2>

<%= pie_chart ({ Intake: @user.entries.todays_entries.map(&:energy).sum,
                   Remaining: @user.target_intake - @user.entries.todays_entries.map(&:energy).sum }),
                   colors: ["#48C774","#DDF5E5"],
                   height: "500px",
                   library: {fontSize: "30px"}
                  %>
  <%= pie_chart ({ Protein: @user.entries.todays_entries.map(&:protein).sum,
                   Carbohydrate: @user.entries.todays_entries.map(&:carb).sum, 
                   Fat: @user.entries.todays_entries.map(&:fat).sum }),
                   colors: ["#34B5E1", "#FFDD57", "#FD5F7E"],
                   donut: true %>

<br>
<br>

<div class="tile is-ancestor">
  <div class="tile is-vertical is-parent is-vertical">
    <% @user.entries.todays_entries.each do |entry| %>

      <div class="tile is-child notification is-light">

        <p class="title"><%= entry.name %></p>
        <p class="subtitle"><%= entry.energy %> Kcal</p>

        <div class="subtitle is-6">
          <%= entry.protein %> P | <%= entry.carb %> C | <%= entry.fat %> F
        </div>

        <nav class="level is-mobile">
          <div class="level-left">
            <%= link_to edit_item_path(entry.id),
                        class: "level-item",
                        "aria-label": "edit" do %>

              <span class="icon is-small">
                <%= fa_icon "edit" %>
              </span>

            <% end %>
            
            <%= link_to item_path(entry.id), 
                        method: "delete",
                        remote: "true",
                        class: "level-item delete-item",
                        "aria-label": "delete" do %>
              <span class="icon is-small">
                <%= fa_icon "trash" %>
                <%= hidden_field_tag entry.id,  entry.entry.date  %>
              </span>
              
            <% end %>
          </div>
        </nav>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/_update.html.erb
<h1 class="title is-1">
  
  <% if @current_user.name.present? %>
    Hi <%= @current_user.name.split.first %>!
  <% else %>
    Hi!
  <% end %>
  
</h1>

<h2 class="subtitle is-3">
  You're viewing <%= @date.strftime("%A, %e %b") %>
</h2>

<%= pie_chart ({ Intake: @user.entries.specific_entries(@date).map(&:energy).sum,
                   Remaining: @user.target_intake - @user.entries.specific_entries(@date).map(&:energy).sum }),
                   colors: ["#48C774","#DDF5E5"],
                   height: "500px",
                   library: {fontSize: "30px"}
                  %>
<%= pie_chart ({ Protein: @user.entries.specific_entries(@date).map(&:protein).sum,
                  Carbohydrate: @user.entries.specific_entries(@date).map(&:carb).sum, 
                  Fat: @user.entries.specific_entries(@date).map(&:fat).sum }),
                  colors: ["#34B5E1", "#FFDD57", "#FD5F7E"],
                  donut: true %>

<br>
<br>

<div class="tile is-ancestor">
  <div class="tile is-vertical is-parent is-vertical">
    <% @user.entries.specific_entries(@date).each do |entry| %>

      <div class="tile is-child notification is-light">

        <p class="title"><%= entry.name %></p>
        <p class="subtitle"><%= entry.energy %> Kcal</p>

        <div class="subtitle is-6">
          <%= entry.protein %> P | <%= entry.carb %> C | <%= entry.fat %> F
        </div>

        <nav class="level is-mobile">
          <div class="level-left">
            <%= link_to edit_item_path(entry.id),
                        class: "level-item",
                        "aria-label": "edit" do %>

              <span class="icon is-small">
                <%= fa_icon "edit" %>
              </span>

            <% end %>

            <%= link_to item_path(entry.id), 
                        method: "delete",
                        remote: "true",
                        class: "level-item",
                        "aria-label": "delete" do %>

              <span class="icon is-small">
                <%= fa_icon "trash" %>
              </span>
              
            <% end %>
          </div>
        </nav>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<section class="hero is-large is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        UNA
      </h1>
      <h2 class="subtitle">
        Unnamed Nutrition App
      </h2>
    </div>
  </div>
</section>
<div class="tile is-ancestor">
  <div class="tile is-vertical is-8">
    <div class="tile is-parent">
      <article class="tile is-child notification is-light">
        <p><%= link_to "Join", new_user_path, class: 'title login-out' %></p>
        <p><%= link_to "Log In", login_path, class: 'subtitle is-3 login-out' %></p>
      </article>
    </div>
  </div>
  <div class="tile is-parent">
    <article class="tile is-child notification is-light">
      <div class="content">
        <p class="title">Effortless, beautiful nutrition tracking</p>
        <p class="subtitle">Your next goal is within reach with a little help from UNA</p>
      </div>
    </article>
  </div>
</div>

  

app/views/pages/show.html.erb
<%= render partial: 'calendar' %>

<div id="anything">

	<% if params[:date].present? %>
		<%= render partial: 'update'  %>
	<% else %>
		<%= render partial: 'entries' %>
	<% end %>

</div>

<script>

	const $calendar = $( "#datepicker" )
	const changeViewButton = $("#calendar-button")

	$calendar.change( function () {
		$( "#date_value" ).val($calendar.val())
	})

	changeViewButton.click( function () {
		$.get("/today/update", { date: $( "#date_value" ).val() } ).done(function (response) {
			$( "#anything" ).html(response)
		})
	})
	

	$( "#anything" ).on( "click", ".delete-item", function ( event ) {
		const entryDate = $( event.target ).next().val()
		$.get( "/today/update", { date: entryDate } ).done( function ( response ) {
				$( "#anything" ).html( response )
		})
	})

</script>  

  
  

  

app/views/pages/update.html.erb
<%= render partial: 'update' %>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<h1 class="title is-1">Sign In</h1>

<% if flash[:error].present? %>
  <h2 class="notification is-danger"><%= flash[:error] %></h2>
<% end %>

<%= form_tag login_path do %>
  <div class="field">
    <p class="control has-icons-left">
      <%= email_field_tag :email, nil, class: "input is-warning is-rounded is-large", placeholder: "Email" %>
      <span class="icon is-small is-left">
        <%= fa_icon "envelope" %>
      </span>
    </p>
  </div>

  <div class="field">
    <p class="control has-icons-left">
      <%= password_field_tag :password, nil, class: "input is-warning is-rounded is-large", placeholder: "Password" %>
      <span class="icon is-small is-left">
        <%= fa_icon "lock" %>
      </span>
    </p>
  </div>

  <%= submit_tag "Sign in", class: "button is-warning is-rounded is-large" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :name, class: "label"%>
    <div class="control">
      <%= f.text_field :name, required: true, autofocus: true, class: "input is-rounded" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :email, class: "label" %>
    <div class="control">
      <%= f.email_field :email, required: true, class: "input is-rounded" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :gender, class: "label" %>
    <div class="control">
      <%= f.text_field :gender, class: "input is-rounded" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :height, class: "label" %>
    <div class="control">
      <%= f.number_field :height, class: "input is-rounded" %>
    </div>
  </div>
  
  <div class="field">
    <%= f.label :weight, class: "label" %>
    <div class="control">
      <%= f.number_field :weight, class: "input is-rounded" %>
    </div>
  </div>
  
  <div class="field">
    <%= f.label :activity_level, "Activity Level", class: "label" %>
    <div class="control select is-fullwidth is-rounded">
      <%= f.select :activity_level, [ 'Sedentry', 'Semi-Active', 'Active', 'Very-Active' ], {}, class: "select is-fullwidth" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :goal, class: "label" %>
    <div class="control select is-fullwidth is-rounded">
      <%= f.select :goal, [ 'Gain', 'Lose', 'Maintain' ] %>
    </div>
  </div>

  <div class="field">
    <%= f.label :target_intake, "Target Intake", class: "label" %>
    <div class="control">
      <%= f.text_field :target_intake, class: "input is-rounded" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.submit class: "button is-link is-rounded" %>
    </div>
  </div>
  
<% end %>

app/views/users/edit.html.erb
<h1 class="title is-1">Edit your details</h1>
<% if flash[:message].present? %>
  <h3 class="has-text-success"><%= flash[:message] %></h3>  
<% end %>
  
<%= render partial: 'form' %>

app/views/users/new.html.erb
<h1 class="title is-1">Sign Up</h1>

<% if @user.errors.any? %>
  <ol class="notification is-danger">
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for @user do |f| %>
  <div class="field">
    <p class="control has-icons-left">
      <%= f.email_field :email, class: "input is-warning is-rounded is-large", placeholder: "Email" %>
      <span class="icon is-small is-left">
        <%= fa_icon "envelope" %>
      </span>
    </p>
  </div>  

  <div class="field">
    <p class="control has-icons-left">
      <%= f.password_field :password, class: "input is-warning is-rounded is-large", placeholder: "Password" %>
      <span class="icon is-small is-left">
        <%= fa_icon "lock" %>
      </span>
    </p>
  </div>

  <div class="field">
    <p class="control has-icons-left">
      <%= f.password_field :password_confirmation, class: "input is-warning is-rounded is-large", placeholder: "Confirm Password" %>
      <span class="icon is-small is-left">
        <%= fa_icon "lock" %>
      </span>
    </p>
  </div>    
  <%= f.submit "Sign up!", class: "button is-warning is-rounded is-large"%>
<% end %>